# -*- coding: utf-8 -*-
"""DZ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KV76ukoWCRUcnMnic9H2wbhx7YzsddU1
"""

from itertools import permutations
import sys
import math
# расчёт расстояния между 2-я точками
def S(p1,p2):
  return ((p2[0] - p1[0]) ** 2 + (p2[1] - p1[1]) ** 2) ** 0.5
# расчёт длины пути
def Rout(point):
  R=0
  i=0
  for i in range(len(point)-1):
    R+=S(point[i],point[i+1])
  return R+S(point[len(point)-1],point[0])
#массив точек
points=[(0,2),(2,5),(5,2),(6,6),(8,3)]  
i=0;
f=math.factorial(len(points)-1)
min=Rout(points)
for point in permutations(points, 5):
  if Rout(point)<min:
    min=Rout(point)
    tmp=point
  i+=1;
  if i==f:
    break
print(tmp,min)
sys.stdout.write('('+str(tmp[0][0])+','+str(tmp[0][1])+')')
R=0
txt1=''
i=0
while i<len(tmp)-1:
   R+=S(tmp[i],tmp[i+1])
   txt1 += "->({x},{y})[{l}]".format(x=tmp[i+1][0], y=tmp[i+1][1],l=R)
   i+=1
R+=S(tmp[i],tmp[0])
txt1 += "->({x},{y})[{l}]".format(x=tmp[i][0], y=tmp[0][1],l=R)+'='+str(R)
sys.stdout.write(txt1)